name: C/C++ CI

on: [push]
jobs:
  check_changes:
    runs-on: ubuntu-22.04
    outputs:
      cpp_hpp_changed: ${{ steps.filter.outputs.cpp_hpp }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for changes in .cpp and .hpp files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            cpp_hpp:
              - '**/*.cpp'
              - '**/*.hpp'    
  build_cpp:
    runs-on: ubuntu-22.04
    if: needs.check_changes.outputs.cpp_hpp_changed == 'true'
    steps:
    - uses: actions/checkout@v4
    - name: prepare
      run: mkdir build
    - name: cmake
      run: cmake ..
      working-directory: build/
    - name: make
      run: make
      working-directory: ./build
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ReadLineWords
        path: build/ReadLineWords
        retention-days: 2

  build_nginx_docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: ReadLineWords

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BANANA_TESTING_USERNAME }}
          password: ${{ secrets.BANANA_TESTING_TOKEN }}          
          
      - name: Build image
        run: |
          docker build -t banana-testing:latest .
          docker tag ${{ secrets.BANANA_TESTING_USERNAME }}/banana-testing-svinopterix:latest ${{ secrets.BANANA_TESTING_USERNAME }}/banana-testing-svinopterix:${{ github.ref_name }}-${{ github.run_number }}


      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.BANANA_TESTING_USERNAME }}/banana-testing-svinopterix:latest
          docker push ${{ secrets.BANANA_TESTING_USERNAME }}/banana-testing-svinopterix:${{ github.ref_name }}-${{ github.run_number }}